const data = [
  {
    Product_main_image: "clothes/1",
    Product_name: "Dress",
    Product_price: "38",
    category: "cloth",
    id: "1",
    quantity: "1",
    small_image_1: "clothes/1",
    small_image_2: "shop/24",
    small_image_3: "shop/25",
    small_image_4: "shop/26",
    total: "38",
  },
  {
    Product_main_image: "clothes/2",
    Product_name: "Jumpsuit",
    Product_price: "24",
    category: "cloth",
    id: "2",
    quantity: "1",
    small_image_1: "clothes/2",
    small_image_2: "shop/24",
    small_image_3: "shop/25",
    small_image_4: "shop/26",
    total: "24",
  },
  {
    Product_main_image: "clothes/3",
    Product_name: "T-Shirt",
    Product_price: "30",
    category: "cloth",
    id: "3",
    quantity: "1",
    small_image_1: "clothes/3",
    small_image_2: "shop/24",
    small_image_3: "shop/25",
    small_image_4: "shop/26",
    total: "30",
  },
  {
    Product_main_image: "clothes/4",
    Product_name: "Woman Top",
    Product_price: "18",
    category: "cloth",
    id: "4",
    quantity: "1",
    small_image_1: "clothes/4",
    small_image_2: "shop/24",
    small_image_3: "shop/25",
    small_image_4: "shop/26",
    total: "18",
  },
  {
    Product_main_image: "featured/1",
    Product_name: "Adidas",
    Product_price: "98",
    category: "featured",
    id: "5",
    quantity: "1",
    small_image_1: "featured/1",
    small_image_2: "shoes/1",
    small_image_3: "shop/2",
    small_image_4: "shop/3",
    total: "98",
  },
  {
    Product_main_image: "featured/2",
    Product_name: "Puma Shoes",
    Product_price: "56",
    category: "featured",
    id: "6",
    quantity: "1",
    small_image_1: "featured/2",
    small_image_2: "shoes/1",
    small_image_3: "shoes/2",
    small_image_4: "shoes/3",
    total: "56",
  },
  {
    Product_main_image: "featured/3",
    Product_name: "American Tourister Backpacks",
    Product_price: "32",
    category: "featured",
    id: "7",
    quantity: "1",
    small_image_1: "featured/3",
    small_image_2: "shop/24",
    small_image_3: "shop/25",
    small_image_4: "shop/26",
    total: "32",
  },
  {
    Product_main_image: "featured/4",
    Product_name: "Nike Cap",
    Product_price: "25",
    category: "featured",
    id: "8",
    quantity: "1",
    small_image_1: "featured/4",
    small_image_2: "shop/24",
    small_image_3: "shop/25",
    small_image_4: "shop/26",
    total: "25",
  },
  {
    Product_main_image: "shop/1",
    Product_name: "T-Shirt",
    Product_price: "98",
    category: "shop",
    id: "9",
    quantity: "1",
    small_image_1: "shop/1",
    small_image_2: "shop/24",
    small_image_3: "shop/25",
    small_image_4: "shop/26",
    total: "98",
  },
  {
    Product_main_image: "shop/2",
    Product_name: "Puma",
    Product_price: "56",
    category: "shop",
    id: "10",
    quantity: "1",
    small_image_1: "shop/2",
    small_image_2: "shop/24",
    small_image_3: "shop/25",
    small_image_4: "shop/26",
    total: "56",
  },
  {
    Product_main_image: "shop/3",
    Product_name: "Pures",
    Product_price: "32",
    category: "shop",
    id: "11",
    quantity: "1",
    small_image_1: "shop/3",
    small_image_2: "shop/24",
    small_image_3: "shop/25",
    small_image_4: "shop/26",
    total: "32",
  },
  {
    Product_main_image: "shop/4",
    Product_name: "Nike Shoes",
    Product_price: "25",
    category: "shop",
    id: "12",
    quantity: "1",
    small_image_1: "shop/4",
    small_image_2: "shop/24",
    small_image_3: "shop/25",
    small_image_4: "shop/26",
    total: "25",
  },
  {
    Product_main_image: "shop/5",
    Product_name: "Cap",
    Product_price: "98",
    category: "shop",
    id: "13",
    quantity: "1",
    small_image_1: "shop/5",
    small_image_2: "shop/24",
    small_image_3: "shop/25",
    small_image_4: "shop/26",
    total: "98",
  },
  {
    Product_main_image: "shop/6",
    Product_name: "Puma",
    Product_price: "56",
    category: "shop",
    id: "14",
    quantity: "1",
    small_image_1: "shop/6",
    small_image_2: "shop/24",
    small_image_3: "shop/25",
    small_image_4: "shop/26",
    total: "56",
  },
  {
    Product_main_image: "shop/7",
    Product_name: "Shoes",
    Product_price: "32",
    category: "shop",
    id: "15",
    quantity: "1",
    small_image_1: "shop/7",
    small_image_2: "shop/24",
    small_image_3: "shop/25",
    small_image_4: "shop/26",
    total: "32",
  },
  {
    Product_main_image: "shop/8",
    Product_name: "Sweater",
    Product_price: "25",
    category: "shop",
    id: "16",
    quantity: "1",
    small_image_1: "shop/8",
    small_image_2: "shop/24",
    small_image_3: "shop/25",
    small_image_4: "shop/26",
    total: "25",
  },
  {
    Product_main_image: "shop/9",
    Product_name: "Bag",
    Product_price: "32",
    category: "shop",
    id: "17",
    quantity: "1",
    small_image_1: "shop/9",
    small_image_2: "shop/24",
    small_image_3: "shop/25",
    small_image_4: "shop/26",
    total: "32",
  },
  {
    Product_main_image: "shop/10",
    Product_name: "Watch ",
    Product_price: "25",
    category: "shop",
    id: "18",
    quantity: "1",
    small_image_1: "shop/10",
    small_image_2: "shop/24",
    small_image_3: "shop/25",
    small_image_4: "shop/26",
    total: "25",
  },
  {
    Product_main_image: "shop/11",
    Product_name: "Adidas Cap",
    Product_price: "98",
    category: "shop",
    id: "19",
    quantity: "1",
    small_image_1: "shop/11",
    small_image_2: "shop/24",
    small_image_3: "shop/25",
    small_image_4: "shop/26",
    total: "98",
  },
  {
    Product_main_image: "shop/12",
    Product_name: "Puma Shoes",
    Product_price: "56",
    category: "shop",
    id: "20",
    quantity: "1",
    small_image_1: "shop/12",
    small_image_2: "shop/24",
    small_image_3: "shop/25",
    small_image_4: "shop/26",
    total: "56",
  },
  {
    Product_main_image: "shop/13",
    Product_name: "Rolex Watch",
    Product_price: "32",
    category: "shop",
    id: "21",
    quantity: "1",
    small_image_1: "shop/13",
    small_image_2: "shop/24",
    small_image_3: "shop/25",
    small_image_4: "shop/26",
    total: "32",
  },
  {
    Product_main_image: "shop/14",
    Product_name: "Nike Shoes",
    Product_price: "25",
    category: "shop",
    id: "22",
    quantity: "1",
    small_image_1: "shop/14",
    small_image_2: "shop/24",
    small_image_3: "shop/25",
    small_image_4: "shop/26",
    total: "25",
  },
  {
    Product_main_image: "shop/15",
    Product_name: "Adidas cap",
    Product_price: "98",
    category: "shop",
    id: "23",
    quantity: "1",
    small_image_1: "shop/15",
    small_image_2: "shop/24",
    small_image_3: "shop/25",
    small_image_4: "shop/26",
    total: "98",
  },
  {
    Product_main_image: "shop/16",
    Product_name: "Puma",
    Product_price: "56",
    category: "shop",
    id: "24",
    quantity: "1",
    small_image_1: "shop/16",
    small_image_2: "shop/24",
    small_image_3: "shop/25",
    small_image_4: "shop/26",
    total: "56",
  },
  {
    Product_main_image: "shop/17",
    Product_name: "T-Shirt",
    Product_price: "32",
    category: "shop",
    id: "25",
    quantity: "1",
    small_image_1: "shop/17",
    small_image_2: "shop/24",
    small_image_3: "shop/25",
    small_image_4: "shop/26",
    total: "32",
  },
  {
    Product_main_image: "shop/18",
    Product_name: "Nike Cap",
    Product_price: "25",
    category: "shop",
    id: "26",
    quantity: "1",
    small_image_1: "shop/18",
    small_image_2: "shop/24",
    small_image_3: "shop/25",
    small_image_4: "shop/26",
    total: "25",
  },
  {
    Product_main_image: "shop/19",
    Product_name: "Men's T-Shirt",
    Product_price: "32",
    category: "shop",
    id: "27",
    quantity: "1",
    small_image_1: "shop/19",
    small_image_2: "shop/24",
    small_image_3: "shop/25",
    small_image_4: "shop/26",
    total: "32",
  },
  {
    Product_main_image: "shop/20",
    Product_name: "Dreess",
    Product_price: "25",
    category: "shop",
    id: "28",
    quantity: "1",
    small_image_1: "shop/20",
    small_image_2: "shop/24",
    small_image_3: "shop/25",
    small_image_4: "shop/26",
    total: "25",
  },
];
